
<section>
    <header>
        <h1>Order aanpassen #<?php echo $this->order->getOrdernr(); ?></h1>

        <?php if(!empty($this->error)) :?><div class="error"><?php echo $this->error; ?></div><?php endif; ?>
        <div class="right">
            <a href="/klanten/view/id/<?php echo $this->order->getKlant()->getKlantnr(); ?>" class="tip view-client" title="Klant bekijken">Klant bekijken</a>
            <a href="/orders/view/id/<?php echo $this->order->getOrdernr(); ?>" class="tip view-order" title="Order bekijken">Order bekijken</a>
            <a href="/orders/delete/id/<?php echo $this->order->getOrdernr(); ?>" class="tip delete" title="Order verwijderen">Order verwijderen</a>
        </div>
    </header>

    <?php if(!empty($this->error)) :?><div class="error"><?php echo $this->error; ?></div><?php endif; ?>
    <?php echo $this->form; ?>
</section>