
<section>
    <header>
        <h1>Klant aanpassen #<?php echo $this->klant->getKlantnr(); ?></h1>

        <div class="right">
            <a href="/orders/klant/id/<?php echo $this->klant->getKlantnr(); ?>" class="tip view-order" title="Orders van klant">Orders van klant</a>
            <a href="/klanten/view/id/<?php echo $this->klant->getKlantnr(); ?>" class="tip view-client" title="Klant bekijken">Klant bekijken</a>
            <a href="/klanten/delete/id/<?php echo $this->klant->getKlantnr(); ?>" class="tip delete" title="Klant verwijderen">Klant verwijderen</a>
        </div>
    </header>

    <?php if(!empty($this->error)) :?><div class="error"><?php echo $this->error; ?></div><?php endif; ?>
    <?php echo $this->form; ?>
</section>